### ISSUE TITLE
Clear Log does not seem to do anything...

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#1]
Pressing this button on GUI does not clear the log. Just an FYI

**Comment by rrskybox** [comment]
I'll check into it.

**Comment by rrskybox** [comment]
The NightShift Clear Log button clears the NightShift notes on the Notes tab.  It doesn't clear any Humason log.  I probably should disable that button unless the Notes tab is selected, but instead I just changed the label to "Clear Notes" (the lazy solution).
