### ISSUE TITLE
Does it make sense to move the NS target grouping function to IP

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#10]
I was thinking since you added the group target function in NS for targets stored in months folder, maybe it should be moved to the IP tool in the list function or another button called Group for the target swap in and out for that imaging month.

I say this since NS seems to be a staging area of all your tools and you already moved the targets function to IP since its more suited...

Just a thought...

Dale

**Comment by rrskybox** [comment]
I think you're right.  I'll move it over.  Give me a day or two.

**Comment by rrskybox** [comment]
I added Target Group functionality to ImagePlanner, but left it also here in NightShift.  I doesn't hurt anything and might just be useful as a precursor to running Humason, when target list changes or review in ImagePlanner aren't needed. Easier to leave it in that put it back in later for some reason.
