### ISSUE TITLE
Program does not launch on different machine Z800 Win 10

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#2]
Program does not launch on different machine Z800 Win 10. I copied the publish from my Z840 to my Z800 and I notice they install but don't run.. The mini modules run but Nightshift, Humanon and image planner do not. They install but when run, nothing happens. Wierd. Any idea what to check?

Dale

**Comment by rrskybox** [comment]
Nightshift also tries to bring up TSX first thing.  Did you do the "Run once in administrator mode" thing for TSX on this new box?

**Comment by astromiester1** [comment]
Fixed that... Can not install from remote drive.. Had to copy to desktop... Those programs install... You can close this...

**Comment by rrskybox** [comment]
Cool.

**Comment by astromiester1** [comment]
Did some testing tonight live...  Since, I have a OSC, I don't have dark frames but the interface expects me to use one with my image with autodark. You have a checkbox for the guider but not one for the imager so, if I ignore it, it fails the plate solve cause the image is too dark. Would it be easy for me to disable the dark frame for the imager in the code since I have an OSC. 

Thanks
Dale

**Comment by astromiester1** [comment]
Here is the HumanOn Script entry when it dies... Just to get it to move forward I put a dark tee shirt over the dew sheild when it asked me too but still did not work. Maybe, I need to set the image link settings different or do you do anything in your plate solver routine.

Sequence Updated
Running diagnostics
Diagnostics success
Loading first session target plan
Waiting until 22:16
Waiting until 22:16
Initializing system
Connecting
Connecting mount
Connecting camera
Connecting guide camera
Connecting focuser
Devices Connected
Checking for new target to clear meridian
New target is clear of meridian
 ******************* Imaging Target: M81
Disconnecting mount
Initiating coordinate CLS to M81
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: Receive time-out. Error = 209.
CLS Failed: Error 209 -- trying again
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: The astrometric solution failed. Error = 655.
CLS Failed: 655
Aborting and Closing Down
Parking Mount
Disconnecting all devices
Aborting guiding
Shutting down guider temperature regulation, if any
Disconnecting guider
Disconnecting focuser
Aborting imaging
Turning off camera temperature regulation
Disconnecting camera
Disconnecting mount
All TSX devices disconnected
Abort Completed -- awaiting new orders, Captain
