### ISSUE TITLE
Old App NightShift Added All your mini functions // QuickPick has one compile error

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#4]
Yeah, I have been adding your old functions including the reduction group app to the image page of your old app Nightshift which I  assume is replaced with HumanOn..

I added I think all of them except Quickpick because I had a compile error.. I may add the observation on that thread as an fyi. Just wanted to play around with them to see what they do against your descriptions... 

Bye the way, again... Very impressed with your work man.. 
![New GUI Nightshift With MiniFunctions](https://user-images.githubusercontent.com/14363854/218851141-771b8ea6-723e-4902-9aeb-03b0d2b549da.jpg)

**Comment by rrskybox** [comment]
NightShift is really more of a dashboard app as a place to consolidate access to all the other myriad stuff I coded.  I originally intended it as a place where I could look at what I'd been up to on past nights, save things that I wanted to do in the future and log what I'd been up to night to night.  Humason doesn't replace it;  Humason is just one of the apps that you can run from NightShift.  Admittedly the coupling is really pretty loose, though.

Without any pressure, I don't get around to updating this app very often.  If you really want to make some improvements, you might want to consider cloning the project into a local VS Git so we are working off the same code base.   That's what GitHub is really for.

Thanks for the interest.

**Comment by astromiester1** [comment]
Will do. Thanks Dale
