### ISSUE TITLE
Latest build on Repository Image Planner Behavior Question

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#7]
Currently, I believe once you highlight a target in nightshift and hit the image planner button(IP), IP comes up for each target highlighted. Instead, is it possible to just have one IP screen up and as you double cllick on a target the IP updates as well wo opening multiple screens.. The load group works great by the way..

Thanks
Dale

**Comment by rrskybox** [comment]
Although I modified Image Planner to initialize to the target selected in NightShift, each selection of a new target will still launch an instance of Image Planner.   Setting up the required inter-process signalling would probably require creation of an COM interface library and some refactoring of Image Planner.  Given the work, I'm not sure what the benefit is as you can already page through a target list in Image Planner.  I don't understand why you would want to go back and forth to the Night Shift app.  Can you elaborate?

**Comment by astromiester1** [comment]
I sort on nightshift targets based on altitude during the night to prioritize which objects to image first...Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/9/24  9:09 PM  (GMT-05:00) To: rrskybox/Nightshift ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Nightshift] Latest build on Repository Image Planner Behavior Question (Issue #7) 
Although I modified Image Planner to initialize to the target selected in NightShift, each selection of a new target will still launch an instance of Image Planner.   Setting up the required inter-process signalling would probably require creation of an COM interface library and some refactoring of Image Planner.  Given the work, I'm not sure what the benefit is as you can already page through a target list in Image Planner.  I don't understand why you would want to go back and forth to the Night Shift app.  Can you elaborate?
